import { useTheme } from 'react-native-paper'
import { StyleSheet } from 'react-native'
import { useMemo } from 'react'

/**
 * useCommunityStyles - 主题感知的 Community 屏幕样式 Hook
 * 根据当前 Paper 主题（亮色/深色模式）动态生成样式
 * 
 * @returns StyleSheet 对象，所有颜色都从主题获取
 */
export function useCommunityStyles() {
    const { colors } = useTheme()
    
    return useMemo(
        () => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    header: {
        paddingHorizontal: 16,
        paddingVertical: 16,
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
    },
    title: {
        fontSize: 32,
        fontWeight: '800',
        color: colors.onSurface,
    },
    section: {
        marginBottom: 24,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        marginBottom: 12,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: '600',
        color: colors.onSurface,
    },
    buttonGroup: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
        marginLeft: 'auto',
    },
    addButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
    },
    addButtonText: {
        fontSize: 24,
        lineHeight: 24,
        color: colors.onPrimary,
        fontWeight: 'bold',
        textAlign: 'center',
        includeFontPadding: false,
    },
    scrollButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.onPrimary,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.outline,
        marginLeft: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 2,
        elevation: 1,
    },
    scrollButtonText: {
        fontSize: 20,
        lineHeight: 20,
        color: colors.onSurfaceVariant,
        fontWeight: '600',
        textAlign: 'center',
        includeFontPadding: false,
    },
    challengeListContent: {
        paddingHorizontal: 8,
    },
    postButton: {
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 14,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 4,
        elevation: 3,
    },
    postButtonIcon: {
        fontSize: 16,
        color: colors.onPrimary,
        fontWeight: '700',
        marginRight: 6,
    },
    postButtonText: {
        fontSize: 15,
        color: colors.onPrimary,
        fontWeight: '600',
        letterSpacing: 0.3,
    },
    // Challenge Detail Modal
    challengeHeaderCard: {
        paddingHorizontal: 16,
        paddingVertical: 16,
        paddingTop: 12,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    headerContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        paddingRight: 16,
    },
    headerIcon: {
        fontSize: 68,
        marginRight: 16,
        marginBottom: 8,
    },
    headerInfo: {
        flex: 1,
        justifyContent: 'center',
    },
    headerTitle: {
        fontSize: 28,
        fontWeight: '800',
        color: colors.onPrimary,
        marginBottom: 10,
    },
    headerMeta: {
        flexDirection: 'column',
    },
    headerMetaText: {
        fontSize: 16,
        color: colors.onPrimary,
        fontWeight: '500',
        marginBottom: 6,
    },
    closeButtonTop: {
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
    },
    closeButtonIcon: {
        fontSize: 24,
        color: colors.onPrimary,
        fontWeight: '700',
    },
    detailSection: {
        paddingHorizontal: 16,
        marginBottom: 28,
        marginTop: 4,
    },
    detailSectionTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: colors.onSurface,
        marginBottom: 14,
    },
    aboutDescription: {
        fontSize: 16,
        color: colors.onSurfaceVariant,
        lineHeight: 26,
        fontWeight: '400',
    },
    badgeCard: {
        borderRadius: 18,
        padding: 28,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
    },
    badgeIcon: {
        fontSize: 72,
        marginBottom: 18,
    },
    badgeName: {
        fontSize: 20,
        fontWeight: '800',
        color: colors.onSurface,
        marginBottom: 10,
        textAlign: 'center',
    },
    badgeDescription: {
        fontSize: 15,
        color: colors.onSurfaceVariant,
        textAlign: 'center',
        lineHeight: 24,
        fontWeight: '400',
    },
    participantItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
        paddingHorizontal: 0,
    },
    participantAvatar: {
        width: 48,
        height: 48,
        borderRadius: 24,
        marginRight: 14,
        borderWidth: 2,
        borderColor: colors.primary,
    },
    participantInfo: {
        flex: 1,
    },
    participantName: {
        fontSize: 15,
        fontWeight: '600',
        color: colors.onSurface,
        marginBottom: 8,
    },
    progressBar: {
        height: 6,
        backgroundColor: colors.outline,
        borderRadius: 3,
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        backgroundColor: colors.primary,
    },
    progressText: {
        fontSize: 13,
        color: colors.primary,
        fontWeight: '700',
        marginLeft: 12,
        minWidth: 40,
        textAlign: 'right',
    },
    joinChallengeButton: {
        marginHorizontal: 16,
        marginBottom: 12,
        marginTop: 12,
        paddingVertical: 16,
        backgroundColor: colors.primary,
        borderRadius: 14,
        alignItems: 'center',
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 6,
        elevation: 4,
    },
    joinedButton: {
        backgroundColor: 'rgba(139, 168, 136, 0.6)',
    },
    joinChallengeButtonText: {
        fontSize: 16,
        fontWeight: '700',
        color: colors.onPrimary,
        letterSpacing: 0.5,
    },
    // Create Challenge Modal
    challengeModalHeader: {
        backgroundColor: colors.primary,
        paddingTop: 16,
        paddingHorizontal: 16,
        paddingBottom: 20,
        paddingLeft: 16,
        position: 'relative',
    },
    challengeModalCloseText: {
        fontSize: 24,
        color: colors.onPrimary,
        fontWeight: '700',
        marginBottom: 12,
    },
    challengeModalTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    challengeModalIcon: {
        fontSize: 40,
        marginRight: 12,
    },
    challengeModalTitle: {
        fontSize: 28,
        fontWeight: '700',
        color: colors.onPrimary,
    },
    challengeModalSubtitle: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.85)',
        marginTop: 4,
    },
    progressBarContainer: {
        flexDirection: 'row',
        paddingHorizontal: 16,
        paddingVertical: 16,
        backgroundColor: colors.onPrimary,
        borderBottomWidth: 1,
        borderBottomColor: colors.outline,
    },
    progressBarSegment: {
        flex: 1,
        height: 4,
        backgroundColor: colors.outline,
        borderRadius: 2,
        marginRight: 8,
    },
    progressBarSegmentActive: {
        backgroundColor: colors.primary,
    },
    createChallengeContent: {
        paddingHorizontal: 16,
        paddingTop: 24,
        paddingBottom: 40,
    },
    stepContainer: {
        marginBottom: 24,
    },
    stepTitle: {
        fontSize: 22,
        fontWeight: '700',
        color: colors.onSurface,
        marginBottom: 8,
    },
    stepSubtitle: {
        fontSize: 15,
        color: colors.onSurfaceVariant,
        marginBottom: 20,
    },
    backButton: {
        marginBottom: 20,
    },
    backButtonText: {
        fontSize: 15,
        color: colors.primary,
        fontWeight: '600',
    },
    typeCardsContainer: {
    },
    typeCard: {
        flexDirection: 'row',
        backgroundColor: colors.onPrimary,
        borderRadius: 16,
        padding: 14,
        borderWidth: 2,
        borderColor: colors.outline,
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    typeCardIcon: {
        width: 56,
        height: 56,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
        flexShrink: 0,
        marginRight: 14,
    },
    typeCardIconText: {
        fontSize: 28,
    },
    typeCardContent: {
        flex: 1,
        justifyContent: 'center',
    },
    typeCardName: {
        fontSize: 16,
        fontWeight: '700',
        color: colors.onSurface,
        marginBottom: 4,
    },
    typeCardDesc: {
        fontSize: 13,
        color: colors.onSurfaceVariant,
    },
    formGroup: {
        marginBottom: 20,
    },
    formLabelChallenge: {
        fontSize: 15,
        fontWeight: '700',
        color: colors.onSurface,
        marginBottom: 8,
    },
    requiredMark: {
        color: colors.error,
    },
    textInputField: {
        borderWidth: 1,
        borderColor: colors.outline,
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 12,
        fontSize: 15,
        color: colors.onSurface,
        backgroundColor: colors.background,
    },
    formHint: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 6,
    },
    hintText: {
        fontSize: 13,
        color: colors.onSurfaceVariant,
    },
    errorText: {
        fontSize: 13,
        color: colors.error,
    },
    charCountChallenge: {
        fontSize: 13,
        color: colors.onSurfaceVariant,
    },
    durationGrid: {
        marginBottom: 24,
    },
    durationCard: {
        borderWidth: 2,
        borderColor: colors.outline,
        borderRadius: 12,
        padding: 16,
        marginBottom: 10,
        backgroundColor: colors.onPrimary,
    },
    durationCardSelected: {
        borderColor: colors.primary,
        backgroundColor: colors.background,
    },
    durationLabel: {
        fontSize: 16,
        fontWeight: '700',
        color: colors.onSurface,
        marginBottom: 4,
    },
    durationDesc: {
        fontSize: 13,
        color: colors.onSurfaceVariant,
    },
    badgeGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginBottom: 20,
        marginHorizontal: -4,
        justifyContent: 'space-between',
    },
    badgeOption: {
        width: '31%',
        paddingVertical: 14,
        paddingHorizontal: 8,
        borderWidth: 2,
        borderColor: colors.outline,
        borderRadius: 12,
        alignItems: 'center',
        backgroundColor: colors.onPrimary,
        marginBottom: 10,
        marginHorizontal: 4,
    },
    badgeOptionSelected: {
        borderColor: colors.primary,
        backgroundColor: colors.background,
    },
    badgeCircle: {
        width: 50,
        height: 50,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 3,
        elevation: 3,
    },
    badgeEmoji: {
        fontSize: 24,
    },
    badgeNameChallenge: {
        fontSize: 12,
        fontWeight: '700',
        color: colors.onSurface,
        textAlign: 'center',
    },
    previewContainer: {
        marginBottom: 24,
        backgroundColor: colors.surfaceVariant,
        borderRadius: 14,
        padding: 14,
    },
    previewTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: colors.onSurface,
        marginBottom: 10,
        flexDirection: 'row',
        alignItems: 'center',
    },
    previewCard: {
        borderRadius: 14,
        padding: 16,
        paddingBottom: 14,
    },
    previewHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 10,
    },
    previewIcon: {
        fontSize: 36,
        marginRight: 10,
    },
    previewTitle2: {
        fontSize: 18,
        fontWeight: '700',
        color: colors.onPrimary,
        marginBottom: 2,
    },
    previewDuration: {
        fontSize: 13,
        color: 'rgba(255, 255, 255, 0.85)',
    },
    previewDesc: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.9)',
        lineHeight: 22,
    },
    continueButton: {
        backgroundColor: colors.primary,
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: 'center',
        marginBottom: 16,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 3,
    },
    continueButtonDisabled: {
        backgroundColor: colors.outline,
        shadowOpacity: 0.05,
    },
    continueButtonText: {
        fontSize: 16,
        fontWeight: '700',
        color: colors.onPrimary,
    },
    createChallengeButton: {
        backgroundColor: colors.primary,
        paddingVertical: 16,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 12,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 6,
        elevation: 4,
    },
    createChallengeButtonText: {
        fontSize: 16,
        fontWeight: '700',
        color: colors.onPrimary,
        letterSpacing: 0.5,
    },
    // Create Post Modal
    createPostHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 16,
        backgroundColor: colors.primary,
    },
    createPostTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: colors.onPrimary,
    },
    closeCreatePostButton: {
        fontSize: 28,
        color: colors.onPrimary,
        fontWeight: 'bold',
    },
    createPostInputField: {
        borderWidth: 1,
        borderColor: colors.outline,
        borderRadius: 16,
        padding: 12,
        fontSize: 16,
        minHeight: 120,
        backgroundColor: colors.onPrimary,
        color: colors.onSurface,
    },
    charCounterText: {
        fontSize: 12,
        color: colors.onSurfaceVariant,
        marginTop: 8,
        textAlign: 'right',
    },
    imagePickerButtonContainer: {
        borderWidth: 2,
        borderColor: colors.primary,
        borderRadius: 16,
        paddingVertical: 16,
        marginTop: 16,
        justifyContent: 'center',
        alignItems: 'center',
    },
    imagePickerButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.primary,
    },
    mealCategoryTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.onSurface,
        marginTop: 16,
        marginBottom: 12,
    },
    mealGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
    },
    mealOption: {
        width: 160,
        backgroundColor: colors.surfaceVariant,
        borderRadius: 12,
        paddingVertical: 16,
        paddingHorizontal: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
        marginBottom: 12,
    },
    mealEmoji: {
        fontSize: 32,
        marginBottom: 8,
    },
    mealLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.onPrimary,
        textAlign: 'center',
    },
    emojiContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 16,
        marginBottom: 16,
    },
    emojiButton: {
        width: 56,
        height: 56,
        backgroundColor: colors.background,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
        marginBottom: 8,
    },
    emojiText: {
        fontSize: 20,
    },
    createPostActionsContainer: {
        flexDirection: 'row',
        marginBottom: 32,
    },
    cancelButtonStyle: {
        flex: 1,
        backgroundColor: colors.outline,
        borderRadius: 12,
        paddingVertical: 14,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    cancelButtonTextStyle: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.onSurfaceVariant,
    },
    postCreateButton: {
        flex: 1,
        backgroundColor: colors.primary,
        borderRadius: 12,
        paddingVertical: 14,
        justifyContent: 'center',
        alignItems: 'center',
    },
    postCreateButtonDisabled: {
        backgroundColor: colors.outline,
        opacity: 0.5,
    },
    postCreateButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.onPrimary,
    },
    imagePreviewSection: {
        position: 'relative',
        marginTop: 16,
        borderRadius: 16,
        overflow: 'hidden',
    },
    previewImage: {
        width: '100%',
        height: 200,
    },
    deleteImageButton: {
        position: 'absolute',
        top: 8,
        right: 8,
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    deleteImageButtonText: {
        fontSize: 18,
        color: colors.onPrimary,
        fontWeight: 'bold',
    },
        }),
        [colors]
    )
}
